language: c

cache:
  directories:
    - $HOME/travis-cache

matrix:
  include:
    - env: jobname=linux-clang
      os: linux
      compiler: clang
    - env: jobname=linux-gcc
      os: linux
      compiler: gcc
    - env: jobname=s390x
      arch: s390x
      os: linux
      compiler:

before_install: ci/install-dependencies.sh
script: ci/run-build-and-tests.sh
after_failure: ci/print-test-failures.sh

notifications:
  email: false
