language: c

cache:
  directories:
    - $HOME/travis-cache

os: linux
dist: bionic

arch:
  - amd64
  - arm64
  - s390x
  - ppc64le

matrix:
  include:
    - os: osx

script: ci/timestamp.sh

notifications:
  email: false
