language: c

compiler: clang

os: osx
osx_image:
  - xcode6.4
  - xcode7.3
  - xcode8
  - xcode8.3
  - xcode9
  - xcode9.1
  - xcode9.2
  - xcode9.3
  - xcode9.4
  - xcode10
  - xcode10.1
  - xcode10.2
  - xcode10.3
  - xcode11
  - xcode11.1
  - xcode11.2

before_install: ci/install-dependencies.sh
script: echo "do nothing"

notifications:
  email: false
