language: c

cache:
  directories:
    - $HOME/travis-cache

matrix:
  include:
    - env: jobname=arm64
      arch: arm64
      os: linux
      compiler:

before_install: ci/install-dependencies.sh
script: ci/run-build-and-tests.sh
after_failure: ci/print-test-failures.sh

notifications:
  email: false
